// src/components/solid/components.tsx
/** @jsxRuntime classic */
import type { Element as SolidElement, Ref } from 'solid-js'
import type Node from '../../core/Node'
import type { NodeEventMap } from '../../events'
import type { StyleProps } from '../../style/types'
import type { BaseProps, ImageOptions, InputOptions, NodeHandle, ScrollViewHandle, InputHandle } from '../props'
import { createEffect, createSignal, flatten, omit } from 'solid-js'
import { CORE_EVENT } from '../../core/constants'
import { useUI } from './context'
import {
    getImageStyle,
    getInputCaretStyle,
    getInputContentStyle,
    getInputSelection,
    getInputStyle,
    getInputTextStyle,
    getInputTextValue,
    getScrollContentStyle,
    getScrollViewStyle,
    showInputPlaceholder,
    updateInputLayout,
} from '../shared'

export type { StyleProps, StyleName } from '../../style/types'
export type { NodeHandle, ScrollViewHandle, InputHandle } from '../props'
export type ComponentProps<TRef = Node> = BaseProps & { children?: SolidElement; ref?: Ref<TRef> }
export type ImageProps = Omit<ComponentProps, 'style'> & ImageOptions
export type ScrollViewProps = ComponentProps<ScrollViewHandle> & { horizontal?: boolean }
export type InputProps = Omit<ComponentProps<InputHandle>, 'style'> & InputOptions & { style?: StyleProps }

export function View(props: ComponentProps) {
    return <view {...props}>{props.children}</view>
}

export function Text(props: ComponentProps) {
    return <text {...omit(props, 'children')} value={joinText(props.children)} />
}

export function Image({ src, width, height, style, ...props }: ImageProps) {
    const ui = useUI()
    return (
        <view
            {...props}
            style={getImageStyle(ui.resources!, src, {
                ...(width !== undefined && { width }),
                ...(height !== undefined && { height }),
                ...style,
            })}
        />
    )
}

export function ScrollView(props: ScrollViewProps) {
    let main_node!: Node
    let content_node!: Node

    const tree = (
        <view
            ref={main_node}
            {...omit(props, 'ref', 'children', 'horizontal', 'style')}
            style={getScrollViewStyle(props.horizontal ?? false, props.style)}
        >
            <view ref={content_node} style={getScrollContentStyle(props.horizontal ?? false)}>
                {props.children}
            </view>
        </view>
    )

    ;(props.ref as ((handle: ScrollViewHandle) => void) | undefined)?.({
        nodes: { main: main_node, content: content_node },
    })

    return tree
}

export function Input(props: InputProps) {
    const ui = useUI()
    let input_node!: Node
    let content_node!: Node
    let text_node!: Node
    let caret_node!: Node
    let selection_node!: Node
    const [isFocused, setIsFocused] = createSignal(false)
    const [caretVisible, setCaretVisible] = createSignal(true)

    function onFocus(event: NodeEventMap['focus']) {
        setIsFocused(true)
        props.onFocus?.(event)
    }

    function onBlur(event: NodeEventMap['blur']) {
        setIsFocused(false)
        props.onBlur?.(event)
    }

    function onPointerDown(event: NodeEventMap['pointerdown']) {
        event.source_event.preventDefault()
        props.onPointerDown?.(event)
    }

    function focus() {
        input_node.focus()
    }

    function blur() {
        input_node.blur()
    }

    function showPlaceholder() {
        return showInputPlaceholder(props.value, props.placeholder, isFocused())
    }

    function showCaret() {
        return props.caretVisible ?? true
    }

    function showSelection() {
        const { start, end } = getInputSelection(props)
        return isFocused() && end > start
    }

    createEffect(
        () => [isFocused(), showCaret(), props.value, getInputSelection(props).position],
        ([is_focused, show_caret]) => {
            if (!is_focused || !show_caret) {
                return
            }

            setCaretVisible(true)
            const interval_id = setInterval(() => setCaretVisible((visible) => !visible), 500)

            return () => clearInterval(interval_id)
        },
    )

    const tree = (
        <view
            ref={input_node}
            onFocus={onFocus}
            onBlur={onBlur}
            onPointerDown={onPointerDown}
            style={getInputStyle(props.style)}
            {...omit(
                props,
                'ref',
                'style',
                'value',
                'placeholder',
                'placeholderTextColor',
                'caretVisible',
                'caretPosition',
                'selection',
                'selectionColor',
                'onFocus',
                'onBlur',
                'onPointerDown',
            )}
        >
            <view ref={content_node} style={getInputContentStyle(props.style)}>
                {showSelection() && (
                    <view
                        ref={selection_node}
                        style={{
                            position: 'absolute',
                            backgroundColor: props.selectionColor ?? '#3390ff55',
                            pointerEvents: 'none',
                        }}
                    />
                )}
                <text
                    ref={text_node}
                    style={getInputTextStyle(props.style, showPlaceholder(), props.placeholderTextColor ?? '#777777')}
                    value={joinText(getInputTextValue(props.value, props.placeholder, showPlaceholder()))}
                />
                {isFocused() && showCaret() && <view ref={caret_node} style={getInputCaretStyle(props.style, caretVisible())} />}
            </view>
        </view>
    )

    createEffect(
        () => ({
            value: props.value,
            placeholder: props.placeholder,
            style: props.style,
            caretVisible: showCaret(),
            caretPosition: props.caretPosition,
            selection: props.selection,
            is_focused: isFocused(),
        }),
        ({ is_focused, ...options }) => {
            let active = true
            let scheduled = false

            function updateCaret() {
                if (!active) {
                    return
                }

                ui.update()
                updateInputLayout({
                    content: content_node,
                    text: text_node,
                    caret: is_focused && options.caretVisible ? caret_node : null,
                    selection: showSelection() ? selection_node : null,
                }, options, is_focused)
            }

            updateCaret()
            const stopObserving = ui.events_source.on(CORE_EVENT.UPDATED, ({ operations }) => {
                if (operations.needUpdateLayout() && !scheduled) {
                    scheduled = true
                    queueMicrotask(() => {
                        scheduled = false
                        updateCaret()
                    })
                }
            })

            return () => {
                active = false
                stopObserving()
            }
        },
    )

    ;(props.ref as ((handle: InputHandle) => void) | undefined)?.({
        get nodes() {
            return {
                main: input_node,
                content: content_node,
                text: text_node,
                caret: isFocused() && showCaret() ? caret_node : null,
            }
        },
        focus,
        blur,
    })

    return tree
}

// HELPERS

function joinText(children: SolidElement) {
    const values = flatten(children, { skipNonRendered: true })
    return (Array.isArray(values) ? values : [values ?? '']).map(toTextValue).join('')
}

function toTextValue(value: unknown) {
    if (typeof value !== 'string' && typeof value !== 'number') {
        throw new Error('<Text> cannot have children.')
    }

    return value
}

// Local host JSX types; the framework compiler handles the JSX output.
declare namespace React {
    namespace JSX {
        type Element = SolidElement
        interface ElementChildrenAttribute {
            children: {}
        }
        interface IntrinsicElements {
            view: ComponentProps<Node>
            text: ComponentProps<Node> & { value?: string | number | null }
        }
    }
}

// src/components/react/components.tsx
import type { ReactElement, ReactNode, Ref } from 'react'
import type { NodeEventMap } from '../../events'
import type { StyleProps } from '../../style/types'
import type { BaseProps, ImageOptions, InputOptions, NodeHandle, ScrollViewHandle, InputHandle } from '../props'
import { useEffect, useImperativeHandle, useLayoutEffect, useRef, useState } from 'react'
import { CORE_EVENT } from '../../core/constants'
import {
    getImageStyle,
    getInputCaretStyle,
    getInputContentStyle,
    getInputSelection,
    getInputStyle,
    getInputTextStyle,
    getInputTextValue,
    getScrollContentStyle,
    getScrollViewStyle,
    showInputPlaceholder,
    updateInputLayout,
} from '../shared'
import { useUI } from './context'

export type { StyleProps, StyleName } from '../../style/types'
export type { NodeHandle, ScrollViewHandle, InputHandle } from '../props'
export type ComponentProps<TRef = NodeHandle> = BaseProps & { children?: ReactNode; ref?: Ref<TRef> }
export type TextChildren = string | number | boolean | null | undefined | readonly TextChildren[]
export type TextProps = Omit<ComponentProps, 'children'> & { children?: TextChildren }
export type ImageProps = Omit<ComponentProps, 'style'> & ImageOptions
export type ScrollViewProps = ComponentProps<ScrollViewHandle> & { horizontal?: boolean }
export type InputProps = Omit<ComponentProps<InputHandle>, 'style'> & InputOptions & { style?: StyleProps }

export function View(props: ComponentProps): ReactElement {
    return <view {...props}>{props.children}</view>
}

export function Text({ children, ...props }: TextProps): ReactElement {
    return <text {...props} value={joinText(children)} />
}

export function Image({ src, width, height, style, ...props }: ImageProps): ReactElement {
    const ui = useUI()
    return (
        <view
            {...props}
            style={getImageStyle(ui.resources!, src, {
                ...(width !== undefined && { width }),
                ...(height !== undefined && { height }),
                ...style,
            })}
        />
    )
}

export function ScrollView({ ref, children, horizontal = false, style, ...props }: ScrollViewProps): ReactElement {
    const main_ref = useRef<NodeHandle | null>(null)
    const content_ref = useRef<NodeHandle | null>(null)

    useImperativeHandle(
        ref,
        () => ({
            nodes: {
                main: main_ref.current!.nodes.main,
                content: content_ref.current!.nodes.main,
            },
        }),
        [],
    )

    return (
        <view ref={main_ref} {...props} style={getScrollViewStyle(horizontal, style)}>
            <view ref={content_ref} style={getScrollContentStyle(horizontal)}>
                {children}
            </view>
        </view>
    )
}

export function Input({
    ref,
    style = {},
    value,
    placeholder,
    placeholderTextColor: placeholder_text_color = '#777777',
    caretVisible: show_caret = true,
    caretPosition: caret_position,
    selection,
    selectionColor: selection_color = '#3390ff55',
    onFocus,
    onBlur,
    onPointerDown,
    ...props
}: InputProps): ReactElement {
    const ui = useUI()
    const input_ref = useRef<NodeHandle | null>(null)
    const content_ref = useRef<NodeHandle | null>(null)
    const text_ref = useRef<NodeHandle | null>(null)
    const caret_ref = useRef<NodeHandle | null>(null)
    const selection_ref = useRef<NodeHandle | null>(null)
    const [is_focused, setIsFocused] = useState(false)
    const [caret_visible, setCaretVisible] = useState(true)
    const show_placeholder = showInputPlaceholder(value, placeholder, is_focused)
    const { start: selection_start, end: selection_end, position } =
        getInputSelection({ value, caretPosition: caret_position, selection })

    function handleFocus(event: NodeEventMap['focus']) {
        setIsFocused(true)
        onFocus?.(event)
    }

    function handleBlur(event: NodeEventMap['blur']) {
        setIsFocused(false)
        onBlur?.(event)
    }

    function handlePointerDown(event: NodeEventMap['pointerdown']) {
        event.source_event.preventDefault()
        onPointerDown?.(event)
    }

    function focus() {
        input_ref.current!.nodes.main.focus()
    }

    function blur() {
        input_ref.current!.nodes.main.blur()
    }

    useEffect(() => {
        if (!is_focused || !show_caret) {
            return
        }

        setCaretVisible(true)
        const interval_id = setInterval(() => setCaretVisible((visible) => !visible), 500)
        return () => clearInterval(interval_id)
    }, [is_focused, show_caret, value, position])

    useLayoutEffect(() => {
        const content = content_ref.current!.nodes.main
        const text = text_ref.current!.nodes.main
        const caret = caret_ref.current?.nodes.main
        const selection_node = selection_ref.current?.nodes.main
        let active = true
        let scheduled = false

        function updateCaret() {
            if (!active) {
                return
            }

            updateInputLayout(
                { content, text, caret, selection: selection_node },
                { value, placeholder, style, caretVisible: show_caret, caretPosition: position, selection },
                is_focused,
            )
        }

        updateCaret()
        const stopObserving = ui.events_source.on(CORE_EVENT.UPDATED, ({ operations }) => {
            if (operations.needUpdateLayout() && !scheduled) {
                scheduled = true
                queueMicrotask(() => {
                    scheduled = false
                    updateCaret()
                })
            }
        })

        return () => {
            active = false
            stopObserving()
        }
    }, [ui, is_focused, show_caret, position, selection_start, selection_end, value, placeholder, style])

    useImperativeHandle(
        ref,
        () => ({
            get nodes() {
                return {
                    main: input_ref.current!.nodes.main,
                    content: content_ref.current!.nodes.main,
                    text: text_ref.current!.nodes.main,
                    caret: caret_ref.current?.nodes.main ?? null,
                }
            },
            focus,
            blur,
        }),
        [],
    )

    return (
        <view
            ref={input_ref}
            onFocus={handleFocus}
            onBlur={handleBlur}
            onPointerDown={handlePointerDown}
            style={getInputStyle(style)}
            {...props}
        >
            <view ref={content_ref} style={getInputContentStyle(style)}>
                {is_focused && selection_end > selection_start && (
                    <view
                        ref={selection_ref}
                        style={{
                            position: 'absolute',
                            backgroundColor: selection_color,
                            pointerEvents: 'none',
                        }}
                    />
                )}
                <text
                    ref={text_ref}
                    style={getInputTextStyle(style, show_placeholder, placeholder_text_color)}
                    value={joinText(getInputTextValue(value, placeholder, show_placeholder))}
                />
                {is_focused && show_caret && (
                    <view
                        ref={caret_ref}
                        style={getInputCaretStyle(style, caret_visible)}
                    />
                )}
            </view>
        </view>
    )
}

function joinText(children: unknown): string {
    if (children == null || typeof children === 'boolean') {
        return ''
    }
    if (Array.isArray(children)) {
        return children.map(joinText).join('')
    }
    if (typeof children !== 'string' && typeof children !== 'number') {
        throw new Error('<Text> cannot have children.')
    }
    return String(children)
}

// Local host JSX types; the build uses React's automatic JSX runtime.
declare namespace React {
    namespace JSX {
        type Element = ReactElement
        interface ElementChildrenAttribute {
            children: {}
        }
        interface IntrinsicElements {
            view: ComponentProps
            text: Omit<ComponentProps, 'children'> & { value: string }
        }
    }
}
